"""Matching a spoken answer against a closed set of offered options.

The workhorse of a voice flow: the bot offers three appointment times, the caller
says "let's do wednesday", and that has to become ``slot_b`` in about a
millisecond, without an embedding and without an LLM.
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field

from dialogue.results import Ambiguous, Confidence, Evidence, Fit, FitResult, NoFit, NoFitReason
from dialogue.slots import FitContext, Slot
from dialogue.utterance import Utterance, normalize


def _spoken_variants(form: str) -> list[tuple[str, ...]]:
    """Every tokenization of a surface form that speech might plausibly produce.

    A written surface form and its spoken transcript can tokenize differently
    around compounds: "follow-up" normalizes to one token ``followup``, but STT
    routinely emits "follow up" as two. Neither matches the other, so a surface
    map written in natural orthography would silently miss half its hits.

    Registering the variants here rather than asking the map's author to spell out
    every hyphenation keeps the map derivable from the offer, which is the point
    of the surface-map approach.
    """
    variants: list[tuple[str, ...]] = []
    for candidate in (normalize(form), normalize(form.replace("-", " "))):
        if candidate and candidate not in variants:
            variants.append(candidate)
    # A two-token compound is also sayable as one word ("follow up" -> "followup").
    for candidate in list(variants):
        if len(candidate) == 2:
            joined = ("".join(candidate),)
            if joined not in variants:
                variants.append(joined)
    return variants


@dataclass(frozen=True, slots=True, kw_only=True)
class EnumSlot(Slot[str]):
    """A slot whose value must be one of a known set, recognised by surface forms.

    ``surface`` maps each value to the things a caller might say for it::

        EnumSlot(
            name="chosen_slot",
            prompt="Tuesday at 3, Wednesday at 10, or Thursday at 2?",
            surface={
                "slot_a": ["tuesday", "3pm", "the first", "first one"],
                "slot_b": ["wednesday", "10am", "the second", "second one"],
                "slot_c": ["thursday", "2pm", "the last", "third one"],
            },
        )

    That map is generated by the same code that built the offer -- day names,
    times and ordinals are all derivable from the objects being offered -- so it
    is never a hand-maintained synonym list.

    Surface forms are normalized at construction through the same ``normalize``
    the transcript goes through, which is what lets them be written in natural
    spelling ("let's", "follow-up") and still match whatever STT emits.
    """

    surface: Mapping[str, Sequence[str]]

    _phrases: tuple[tuple[str, tuple[str, ...]], ...] = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        phrases: list[tuple[str, tuple[str, ...]]] = []
        seen: set[tuple[str, tuple[str, ...]]] = set()
        for value, forms in self.surface.items():
            for form in forms:
                for tokens in _spoken_variants(form):
                    if (value, tokens) not in seen:
                        seen.add((value, tokens))
                        phrases.append((value, tokens))
        # Longest first, so a specific form claims its words before a shorter one
        # can. Without this, "the first one" would be matched by a bare "one"
        # belonging to a different option, manufacturing an ambiguity that the
        # caller never uttered.
        phrases.sort(key=lambda pair: len(pair[1]), reverse=True)
        object.__setattr__(self, "_phrases", tuple(phrases))

    @property
    def values(self) -> tuple[str, ...]:
        """The permitted values, in the order they were offered."""
        return tuple(self.surface)

    async def fit(self, u: Utterance, ctx: FitContext) -> FitResult:
        hits: dict[str, list[tuple[int, int]]] = {}
        terms: dict[str, list[str]] = {}
        claimed: list[tuple[int, int]] = []

        for value, phrase in self._phrases:
            index = u.find_phrase(phrase)
            if index < 0:
                continue
            token_range = (index, index + len(phrase))
            # Skip a form only when a STRICTLY LONGER form already claimed those
            # words -- "the first one" outranks a bare "one" inside it. Two forms
            # of equal length overlapping is not a conflict to resolve, it is the
            # genuine ambiguity this slot exists to report: if two offered options
            # are both sayable as "tuesday", the caller really was unclear.
            if any(
                token_range[0] < end and start < token_range[1] and (end - start) > len(phrase)
                for start, end in claimed
            ):
                continue
            claimed.append(token_range)
            hits.setdefault(value, []).append(u.span_of(index, len(phrase)))
            terms.setdefault(value, []).append(" ".join(phrase))

        if not hits:
            return NoFit(
                reason=NoFitReason.NO_SURFACE_HIT,
                evidence=Evidence(matcher="EnumSlot.surface"),
            )

        # Report in offer order, so a clarifying re-prompt reads back the way the
        # options were originally presented.
        matched = [v for v in self.surface if v in hits]

        if len(matched) > 1:
            return Ambiguous(
                slot=self.name,
                candidates=tuple(matched),
                evidence=Evidence(
                    matcher="EnumSlot.surface",
                    spans=tuple(span for v in matched for span in hits[v]),
                    matched_terms=tuple(term for v in matched for term in terms[v]),
                    notes=f"{len(matched)} options matched; refusing to guess",
                ),
            )

        value = matched[0]
        return Fit(
            slot=self.name,
            value=value,
            confidence=Confidence.HIGH,
            evidence=Evidence(
                matcher="EnumSlot.surface",
                spans=tuple(hits[value]),
                matched_terms=tuple(terms[value]),
            ),
        )
