#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Sarvam saaras:v3-realtime (Speech-to-Text, Hinglish codemix mode)
- LM Studio (LLM, local, OpenAI-compatible)
- Sarvam bulbul:v3 (Text-to-Speech, speaks code-mixed Devanagari+Latin natively)

Run the bot using::

    uv run bot.py
"""

import os
import sys
from functools import lru_cache
from pathlib import Path

# Windows consoles default to cp1252; Pipecat's banners and logs are UTF-8.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

import aiohttp
from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransportParams
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.google.vertex.llm import GoogleVertexLLMService
from pipecat.services.sarvam.stt import SarvamRealtimeSTTService
from pipecat.services.sarvam.tts import SarvamTTSService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams
from pipecat.workers.runner import WorkerRunner
from pydantic import BaseModel

from flows import SessionDeps
from flows.command_processor import CommandProcessor
from flows.commands import CommandBatch
from language import (
    Band,
    LanguageBandTracker,
    LanguageMirrorProcessor,
    directive_for_band,
    short_hint_for_band,
)
from rag import QAIndex
from store.clock import IstClock
from store.domain import PhoneNumber
from store.sqlite import SqliteSupportStore
from transcript import ConversationTranscript, ConversationTranscriptProcessor

load_dotenv(override=True)

# daily-python ships no Windows wheels, so the Daily transport is unavailable on a
# Windows dev machine. It is installed (and this import succeeds) in the Linux deploy
# image; locally, use `-t webrtc` or `-t eval` instead.
try:
    from pipecat.transports.daily.transport import DailyParams

    DAILY_AVAILABLE = True
except ImportError:  # pragma: no cover - platform dependent
    DAILY_AVAILABLE = False


@lru_cache(maxsize=1)
def qa_index() -> QAIndex:
    """The Q&A index, embedded once per process and shared across sessions."""
    return QAIndex.load(Path(__file__).parent / "rag" / "corpus" / "qa.json")


class CallInfo(BaseModel):
    """Caller details fetched from the Twilio REST API."""

    from_number: str | None = None
    to_number: str | None = None


async def get_call_info(call_sid: str | None) -> CallInfo | None:
    """Fetch call information from the Twilio REST API using aiohttp.

    Args:
        call_sid: The Twilio call SID (e.g. call_data.call_id), or None.

    Returns:
        A CallInfo with the caller's numbers, or None if it couldn't be fetched.
    """
    if not call_sid:
        return None

    account_sid = os.getenv("TWILIO_ACCOUNT_SID")
    auth_token = os.getenv("TWILIO_AUTH_TOKEN")

    if not account_sid or not auth_token:
        logger.warning("Missing Twilio credentials, cannot fetch call info")
        return None

    url = f"https://api.twilio.com/2010-04-01/Accounts/{account_sid}/Calls/{call_sid}.json"

    try:
        # Use HTTP Basic Auth with aiohttp
        auth = aiohttp.BasicAuth(account_sid, auth_token)

        async with aiohttp.ClientSession() as session:
            async with session.get(url, auth=auth) as response:
                if response.status != 200:
                    error_text = await response.text()
                    logger.error(f"Twilio API error ({response.status}): {error_text}")
                    return None

                data = await response.json()

                return CallInfo(from_number=data.get("from"), to_number=data.get("to"))

    except Exception as e:
        logger.error(f"Error fetching call info from Twilio: {e}")
        return None


async def run_bot(
    transport: BaseTransport, runner_args: RunnerArguments, caller_number: str | None = None
) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
        caller_number: The caller's phone number from Twilio caller ID, if any.
            A match against the store skips phone verification.
    """
    logger.info("Starting bot")

    # Per-session dependencies: the mock order store (seeded fresh in memory —
    # the production seam is the SupportStore Protocol, not this class) and
    # the shared language tracker.
    language_tracker = LanguageBandTracker()
    transcript = ConversationTranscript(
        Path(__file__).parent / "logs" / "transcripts",
        getattr(runner_args, "session_id", None),
    )
    deps = SessionDeps(
        store=SqliteSupportStore.seeded_in_memory(IstClock()),
        tracker=language_tracker,
        clock=IstClock(),
        transcript=transcript,
    )
    caller_phone: PhoneNumber | None = None
    if caller_number:
        try:
            caller_phone = PhoneNumber.parse(caller_number)
        except ValueError:
            logger.info("Caller number {} not usable for lookup", caller_number)

    # Late-bound: the FlowManager needs the worker, which needs the pipeline,
    # which needs these processors — closures read it after construction.
    flow_manager: FlowManager | None = None

    # Speech-to-Text: Sarvam realtime (saaras:v3-realtime), codemix mode for Hinglish.
    # Server-side VAD does the endpointing; should_interrupt=False keeps backchannels
    # ("haan", "achha") from barging in while the bot is speaking.
    stt = SarvamRealtimeSTTService(
        api_key=os.getenv("SARVAM_API_KEY"),
        should_interrupt=False,
        settings=SarvamRealtimeSTTService.Settings(
            language_code=os.getenv("SARVAM_STT_LANGUAGE", "auto"),
            mode="codemix",
            stream_type="fast",
        ),
    )

    # Text-to-Speech: Sarvam bulbul:v3 speaks code-mixed Devanagari+Latin in one pass,
    # so one voice covers any Hindi/English blend. The service defaults to bulbul:v2 —
    # the model must be set explicitly.
    # Sarvam bulbul:v3 defaults to a 24 kHz output; forcing 8 kHz makes the
    # delivered PCM sound garbled/static even when the TTS backend is working.
    tts = SarvamTTSService(
        api_key=os.getenv("SARVAM_API_KEY"),
        sample_rate=int(os.getenv("SARVAM_TTS_SAMPLE_RATE", "24000")),
        settings=SarvamTTSService.Settings(
            model=os.getenv("SARVAM_TTS_MODEL", "bulbul:v3"),
            voice=os.getenv("SARVAM_TTS_VOICE", "shubh"),
            language="hi-IN",
            min_buffer_size=20,
        ),
    )

    # LLM service: Gemini through Vertex AI using a service-account credential.
    vertex_project_id = os.getenv("VERTEX_PROJECT_ID", "gen-lang-client-0158129197")
    vertex_credentials_path = os.getenv(
        "VERTEX_CREDENTIALS_PATH",
        r"C:\Users\Aaditya Bisaria\Voice_Agent\gen-lang-client-0158129197-ad61d3eddc83.json",
    )
    if not Path(vertex_credentials_path).is_file():
        raise RuntimeError(
            "VERTEX_CREDENTIALS_PATH must point to a Google service-account JSON file"
        )
    llm = GoogleVertexLLMService(
        project_id=vertex_project_id,
        credentials_path=vertex_credentials_path,
        location=os.getenv("VERTEX_LOCATION", "asia-south1"),
        settings=GoogleVertexLLMService.Settings(
            model=os.getenv("VERTEX_MODEL", "gemini-2.5-flash"),
            system_instruction=(
                "You are a friendly customer-support voice assistant that "
                "answers questions from Aryan Retail's public help pages about returns, "
                "refunds, replacements, and deliveries. Your responses will be spoken aloud, so avoid emojis, "
                "bullet points, or other formatting that can't be spoken. Keep replies "
                "to one or two short sentences. "
                "You speak both English and Hinglish. Always follow the current "
                "[LANG-STYLE] directive for how much Hindi versus English to use. "
                "For knowledge questions, answer ONLY from the [RAG] context provided "
                "for the current question; if it says there is no answer, say plainly "
                "that you don't have that information — never invent policies, "
                "timelines, or amounts. "
                "When functions are available for what the user asked, call the "
                "matching function instead of describing it. Never say function or "
                "tool names out loud. When told to read back a confirmation, speak "
                "it exactly as given."
            ),
            # Greedy decoding: tool-calling at flow nodes must be dependable
            # and reproducible — a 4B model with sampling will sometimes chat
            # instead of calling the matching function, and evals need the
            # same branch every run.
            temperature=0.0,
            extra={'response_mime_type': 'application/json',
                   'response_json_schema': CommandBatch.model_json_schema()},
        ),
    )

    system_instruction = getattr(getattr(llm, "_settings", None), "system_instruction", None)
    if isinstance(system_instruction, str):
        transcript.log_turn("system", system_instruction)

    # Mirrors the caller's Hindi/English mix by swapping a [LANG-STYLE]
    # directive in the context whenever their language band changes. The
    # tracker is shared with the RAG processor and every flow node, which
    # repeat the current band as a one-line hint near the generation point —
    # the instruction a small model actually follows.
    language_mirror = LanguageMirrorProcessor(tracker=language_tracker)
    user_transcript = ConversationTranscriptProcessor(transcript=transcript, role="user")
    assistant_transcript = ConversationTranscriptProcessor(transcript=transcript, role="assistant")

    # Deterministic gates in front of the LLM: while a confirm or phone-verify
    # node is active, the user's turn is classified by a dialogue Slot before
    # it can reach the model.
    command_processor = CommandProcessor(llm=llm, deps=deps, index=qa_index())

    # Grounds knowledge questions in the Aryan Retail help corpus, but only at
    # KB-capable nodes — mid-flow turns clear stale grounding instead, so a
    # "say you don't have that information" directive never leaks into a
    # slot-collection turn. Retrieval runs speculatively on interim
    # transcripts, so the finished turn pays ~0 added latency.

    context = LLMContext()
    aggregator_pair = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
            user_turn_stop_timeout=3.0,
            user_idle_timeout=12.0,
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            language_mirror,
            user_transcript,
            aggregator_pair.user(),
            command_processor,
            assistant_transcript,
            tts,
            transport.output(),
            aggregator_pair.assistant(),
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
            audio_in_sample_rate=8000,
            audio_out_sample_rate=24000,
        ),
        app_resources=deps,
    )


    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        # Every connection is a new call: fresh mock data, fresh identity,
        # fresh language estimate, no armed gate. (The eval transport reuses
        # this session across runs, so this is also what keeps runs isolated.)
        deps.store = SqliteSupportStore.seeded_in_memory(IstClock())
        deps.customer = await deps.store.customer_by_phone(caller_phone) if caller_phone else None
        if deps.customer:
            logger.info("Caller ID matched customer {}", deps.customer.name)
        deps.verify_attempts = 0
        deps.wip.clear()
        language_tracker.reset()
        from flows.runtime import CommandRuntime
        command_processor.runtime = CommandRuntime(deps)
        command_processor.generation += 1

        # A new call also gets a clean conversation history, then the starting
        # language directive, then the flow graph takes over: verified Twilio
        # callers land in triage greeted by name, everyone else starts at the
        # KB-capable greeting node.
        context.set_messages([])
        context.add_message({"role": "developer", "content": directive_for_band(Band.HINGLISH)})
        transcript.log_turn("developer", directive_for_band(Band.HINGLISH))
        await command_processor.greet()

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # create_transport sets the twilio serializer and add_wav_header automatically.
        "twilio": lambda: FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    if DAILY_AVAILABLE:
        transport_params["daily"] = lambda: DailyParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        )

    transport = await create_transport(runner_args, transport_params)

    # OPTIONAL personalization: create_transport parsed the Twilio websocket, so the
    # call data is on runner_args.call_data. Look up the caller via the Twilio REST API
    # to personalize the conversation (e.g. fetch customer info from your own backend).
    call_data = runner_args.call_data
    call_info = await get_call_info(call_data.call_id) if call_data else None
    if call_info:
        logger.info(f"Call from: {call_info.from_number} to: {call_info.to_number}")

    await run_bot(transport, runner_args, call_info.from_number if call_info else None)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
