#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Sarvam saaras:v3-realtime (Speech-to-Text, Hinglish codemix mode)
- LM Studio (LLM, local, OpenAI-compatible)
- Sarvam bulbul:v3 (Text-to-Speech, speaks code-mixed Devanagari+Latin natively)

Run the bot using::

    uv run bot.py
"""

import os
import sys
from functools import lru_cache
from pathlib import Path

# Windows consoles default to cp1252; Pipecat's banners and logs are UTF-8.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

import aiohttp
from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransportParams
from pipecat.flows import FlowManager
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.services.sarvam.stt import SarvamRealtimeSTTService
from pipecat.services.sarvam.tts import SarvamTTSService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams
from pipecat.workers.runner import WorkerRunner
from pydantic import BaseModel

import flows
from flows import SessionDeps, SlotGateProcessor
from language import (
    Band,
    LanguageBandTracker,
    LanguageMirrorProcessor,
    directive_for_band,
    short_hint_for_band,
)
from rag import QAIndex, RAGGroundingProcessor
from store.clock import IstClock
from store.domain import PhoneNumber
from store.sqlite import SqliteSupportStore

load_dotenv(override=True)

# daily-python ships no Windows wheels, so the Daily transport is unavailable on a
# Windows dev machine. It is installed (and this import succeeds) in the Linux deploy
# image; locally, use `-t webrtc` or `-t eval` instead.
try:
    from pipecat.transports.daily.transport import DailyParams

    DAILY_AVAILABLE = True
except ImportError:  # pragma: no cover - platform dependent
    DAILY_AVAILABLE = False


@lru_cache(maxsize=1)
def qa_index() -> QAIndex:
    """The Q&A index, embedded once per process and shared across sessions."""
    return QAIndex.load(Path(__file__).parent / "rag" / "corpus" / "qa.json")


class CallInfo(BaseModel):
    """Caller details fetched from the Twilio REST API."""

    from_number: str | None = None
    to_number: str | None = None


async def get_call_info(call_sid: str | None) -> CallInfo | None:
    """Fetch call information from the Twilio REST API using aiohttp.

    Args:
        call_sid: The Twilio call SID (e.g. call_data.call_id), or None.

    Returns:
        A CallInfo with the caller's numbers, or None if it couldn't be fetched.
    """
    if not call_sid:
        return None

    account_sid = os.getenv("TWILIO_ACCOUNT_SID")
    auth_token = os.getenv("TWILIO_AUTH_TOKEN")

    if not account_sid or not auth_token:
        logger.warning("Missing Twilio credentials, cannot fetch call info")
        return None

    url = f"https://api.twilio.com/2010-04-01/Accounts/{account_sid}/Calls/{call_sid}.json"

    try:
        # Use HTTP Basic Auth with aiohttp
        auth = aiohttp.BasicAuth(account_sid, auth_token)

        async with aiohttp.ClientSession() as session:
            async with session.get(url, auth=auth) as response:
                if response.status != 200:
                    error_text = await response.text()
                    logger.error(f"Twilio API error ({response.status}): {error_text}")
                    return None

                data = await response.json()

                return CallInfo(from_number=data.get("from"), to_number=data.get("to"))

    except Exception as e:
        logger.error(f"Error fetching call info from Twilio: {e}")
        return None


async def run_bot(
    transport: BaseTransport, runner_args: RunnerArguments, caller_number: str | None = None
) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
        caller_number: The caller's phone number from Twilio caller ID, if any.
            A match against the store skips phone verification.
    """
    logger.info("Starting bot")

    # Per-session dependencies: the mock order store (seeded fresh in memory —
    # the production seam is the SupportStore Protocol, not this class) and
    # the shared language tracker.
    language_tracker = LanguageBandTracker()
    deps = SessionDeps(
        store=SqliteSupportStore.seeded_in_memory(IstClock()),
        tracker=language_tracker,
        clock=IstClock(),
    )
    caller_phone: PhoneNumber | None = None
    if caller_number:
        try:
            caller_phone = PhoneNumber.parse(caller_number)
        except ValueError:
            logger.info("Caller number {} not usable for lookup", caller_number)

    # Late-bound: the FlowManager needs the worker, which needs the pipeline,
    # which needs these processors — closures read it after construction.
    flow_manager: FlowManager | None = None

    # Speech-to-Text: Sarvam realtime (saaras:v3-realtime), codemix mode for Hinglish.
    # Server-side VAD does the endpointing; should_interrupt=False keeps backchannels
    # ("haan", "achha") from barging in while the bot is speaking.
    stt = SarvamRealtimeSTTService(
        api_key=os.getenv("SARVAM_API_KEY"),
        should_interrupt=False,
        settings=SarvamRealtimeSTTService.Settings(
            language_code=os.getenv("SARVAM_STT_LANGUAGE", "auto"),
            mode="codemix",
            stream_type="fast",
        ),
    )

    # Text-to-Speech: Sarvam bulbul:v3 speaks code-mixed Devanagari+Latin in one pass,
    # so one voice covers any Hindi/English blend. The service defaults to bulbul:v2 —
    # the model must be set explicitly.
    # Sarvam bulbul:v3 defaults to a 24 kHz output; forcing 8 kHz makes the
    # delivered PCM sound garbled/static even when the TTS backend is working.
    tts = SarvamTTSService(
        api_key=os.getenv("SARVAM_API_KEY"),
        sample_rate=int(os.getenv("SARVAM_TTS_SAMPLE_RATE", "24000")),
        settings=SarvamTTSService.Settings(
            model=os.getenv("SARVAM_TTS_MODEL", "bulbul:v3"),
            voice=os.getenv("SARVAM_TTS_VOICE", "aditya"),
            language="hi-IN",
            min_buffer_size=20,
        ),
    )

    # LLM service - a local model served by LM Studio, which exposes an
    # OpenAI-compatible API, so OpenAILLMService talks to it via base_url.
    # LM Studio ignores the key, but the OpenAI client requires a non-empty one.
    llm = OpenAILLMService(
        api_key=os.getenv("LLM_API_KEY", "lm-studio"),
        base_url=os.getenv("LLM_BASE_URL", "http://127.0.0.1:1234/v1"),
        settings=OpenAILLMService.Settings(
            model=os.getenv("LLM_MODEL", "google/gemma-4-e4b"),
            system_instruction=(
                "You are a friendly customer-support voice assistant for a demo that "
                "answers questions from Amazon.in's public help pages about returns, "
                "refunds, replacements, and deliveries. You are a demo assistant, not "
                "Amazon itself. Your responses will be spoken aloud, so avoid emojis, "
                "bullet points, or other formatting that can't be spoken. Keep replies "
                "to one or two short sentences. "
                "You speak both English and Hinglish. Always follow the current "
                "[LANG-STYLE] directive for how much Hindi versus English to use. "
                "For knowledge questions, answer ONLY from the [RAG] context provided "
                "for the current question; if it says there is no answer, say plainly "
                "that you don't have that information — never invent policies, "
                "timelines, or amounts. "
                "When functions are available for what the user asked, call the "
                "matching function instead of describing it. Never say function or "
                "tool names out loud. When told to read back a confirmation, speak "
                "it exactly as given."
            ),
            # Greedy decoding: tool-calling at flow nodes must be dependable
            # and reproducible — a 4B model with sampling will sometimes chat
            # instead of calling the matching function, and evals need the
            # same branch every run.
            temperature=0.0,
            # gemma-4 is a reasoning model: left on, it spends its first hundred
            # tokens thinking before a single word reaches TTS. Turning it off
            # keeps the turn latency conversational.
            extra={"reasoning_effort": "none"},
        ),
    )

    # Mirrors the caller's Hindi/English mix by swapping a [LANG-STYLE]
    # directive in the context whenever their language band changes. The
    # tracker is shared with the RAG processor and every flow node, which
    # repeat the current band as a one-line hint near the generation point —
    # the instruction a small model actually follows.
    language_mirror = LanguageMirrorProcessor(tracker=language_tracker)

    # Deterministic gates in front of the LLM: while a confirm or phone-verify
    # node is active, the user's turn is classified by a dialogue Slot before
    # it can reach the model.
    slot_gate = SlotGateProcessor(get_flow_manager=lambda: flow_manager)

    # Grounds knowledge questions in the Amazon.in help corpus, but only at
    # KB-capable nodes — mid-flow turns clear stale grounding instead, so a
    # "say you don't have that information" directive never leaks into a
    # slot-collection turn. Retrieval runs speculatively on interim
    # transcripts, so the finished turn pays ~0 added latency.
    rag_grounding = RAGGroundingProcessor(
        index=qa_index(),
        language_hint=lambda: short_hint_for_band(language_tracker.band),
        is_active=lambda: flows.is_rag_active(flow_manager),
    )

    context = LLMContext()
    aggregator_pair = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
            user_turn_stop_timeout=3.0,
            user_idle_timeout=12.0,
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            language_mirror,
            slot_gate,
            rag_grounding,
            aggregator_pair.user(),
            llm,
            tts,
            transport.output(),
            aggregator_pair.assistant(),
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
            audio_in_sample_rate=8000,
            audio_out_sample_rate=24000,
        ),
        app_resources=deps,
    )

    flow_manager = FlowManager(
        llm=llm,
        context_aggregator=aggregator_pair,
        worker=worker,
        transport=transport,
    )
    flow_manager.state["deps"] = deps

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        # Every connection is a new call: fresh mock data, fresh identity,
        # fresh language estimate, no armed gate. (The eval transport reuses
        # this session across runs, so this is also what keeps runs isolated.)
        deps.store = SqliteSupportStore.seeded_in_memory(IstClock())
        deps.customer = await deps.store.customer_by_phone(caller_phone) if caller_phone else None
        if deps.customer:
            logger.info("Caller ID matched customer {}", deps.customer.name)
        deps.verify_attempts = 0
        deps.wip.clear()
        language_tracker.reset()
        flow_manager.state.pop(flows.GATE_STATE_KEY, None)

        # A new call also gets a clean conversation history, then the starting
        # language directive, then the flow graph takes over: verified Twilio
        # callers land in triage greeted by name, everyone else starts at the
        # KB-capable greeting node.
        context.set_messages([])
        context.add_message({"role": "developer", "content": directive_for_band(Band.HINGLISH)})
        initial = await flows.build_initial_node(deps, flow_manager)
        if flow_manager.current_node is None:
            await flow_manager.initialize(initial)
        else:
            # A FlowManager initializes once; later connections re-enter via a
            # normal node transition (which also re-greets).
            await flow_manager.set_node_from_config(initial)

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # create_transport sets the twilio serializer and add_wav_header automatically.
        "twilio": lambda: FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    if DAILY_AVAILABLE:
        transport_params["daily"] = lambda: DailyParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        )

    transport = await create_transport(runner_args, transport_params)

    # OPTIONAL personalization: create_transport parsed the Twilio websocket, so the
    # call data is on runner_args.call_data. Look up the caller via the Twilio REST API
    # to personalize the conversation (e.g. fetch customer info from your own backend).
    call_data = runner_args.call_data
    call_info = await get_call_info(call_data.call_id) if call_data else None
    if call_info:
        logger.info(f"Call from: {call_info.from_number} to: {call_info.to_number}")

    await run_bot(transport, runner_args, call_info.from_number if call_info else None)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
